env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - secure: kg5TFTNojZ9VOYHApONRUXSbwu+erLs3WSNNX/CKbkO8eQnBo+1koXHnEtOTQ641YRAVpFLX4QK7pbRfmWWWzR6ntNgXmvE4IUa1ggsUlcorApLq+cQin1Tp1es0/Ul0nYLJN8WXbcObKSLy8FOmHkrMWYuffMtH9e7qEL01ei0=

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8
      env: JOB=Xcode8

install:
  - carthage bootstrap --use-submodules --no-build
  - pod repo update --silent

script:
  - if [[ "$JOB" == "Xcode7.3" ]]; then pod lib lint; fi
  - set -o pipefail
  - xcodebuild test -workspace APIKit.xcworkspace -scheme APIKit | xcpretty -c
  - xcodebuild test -workspace APIKit.xcworkspace -scheme APIKit -sdk iphonesimulator -destination "name=iPhone 6s" | xcpretty -c
  - xcodebuild test -workspace APIKit.xcworkspace -scheme APIKit -sdk appletvsimulator -destination "name=Apple TV 1080p" | xcpretty -c
  - carthage build --no-skip-current

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - carthage archive APIKit

deploy:
  provider: releases
  api_key:
    secure: I/cUbYW2BO/Yej52SHoHEmsjhP27jZuQl7tTvjliNzDAmEeYp6HR4fMnxUUUqcntaqrk6ZJauQ0GjbcDqkekPUAZAaUCsT5kh0qqGK8yMpSTd+FhBHNjqOvPimwGqKn9HOmGIJQnH8LqG+1esZhvhQEJJ0rpRSvapETUIcrZewI=
  file: APIKit.framework.zip
  skip_cleanup: true
  on:
    repo: ishkawa/APIKit
    tags: true
    condition: $JOB = Xcode7.3

notifications:
  email: false
